import "oaidl.idl";
import "ocidl.idl";
import "dxgi.idl";

[uuid("CC94E919-0966-4646-92EC-F74AFE2AB6CB"), object, local, pointer_default( unique )]
interface IFileMesh: IUnknown
{
};

[uuid("5F9E1858-181B-4FC4-B66C-1576FE97F20A"), object, local, pointer_default( unique )]
interface IFileAnimation: IUnknown
{
};

[uuid("1083981E-C631-4A1B-B5A4-12BA2FEFFD15"), object, local, pointer_default( unique )]
interface IMesh: IUnknown
{
	UINT GetNumOfMaterial();
	HRESULT GetDefaultMaterialTexturePath([in] UINT index, [out] WCHAR* texturePathBuffer, [in] UINT bufferLength);
	HRESULT GetNumOfAnimation([out] UINT* pNumOfAnimation);
	HRESULT GetAnimation([in] UINT index, [out] IFileAnimation** ppAnimation);
	HRESULT CopyVertexArray([in] PVOID buff, [in] UINT buffByteWidth);
	UINT GetVretexByteWidth();
};

[uuid("8C54E9F9-5CCA-4EB1-9F92-C6086BD7EE11"), object, local, pointer_default( unique )]
interface ITexture: IUnknown
{
	HRESULT GetFormat([out] DXGI_FORMAT* pFormat);
	HRESULT GetSize([out] UINT* pWidth, [out] UINT* pHeight);
};

[uuid("16D6C23B-423B-45CC-BB2D-ECA889E790D8"), object, local, pointer_default( unique )]
interface IAssetManager: IUnknown
{
	HRESULT LoadMeshFromFile([in] const WCHAR* meshFilePath, [out] IMesh** ppMesh);
	HRESULT LoadTextureFromFile([in] const WCHAR* textureFilePath, [out] ITexture** ppTexture);
};

[uuid("1AB5D7BD-279E-43C9-9941-09C4F33D6001"), object, local, pointer_default( unique )]
interface IMeshRenderer: IUnknown
{
	HRESULT GetMesh([out] IMesh** pMesh);
	HRESULT SetMesh([in] IMesh* pMesh);
	UINT GetNumOfMaterial();
	HRESULT SetMaterial([in] UINT materialId, [in] ITexture* pTexture);
	HRESULT GetMaterial([in] UINT materialId, [out] ITexture** ppTexture);
	HRESULT SetWorldMatrix([in] PVOID pMatrix);
	HRESULT Realize();
};

[uuid("C8528400-E8AD-4B9B-8EF5-AFE6AF81ABE9"), object, local, pointer_default( unique )]
interface ISkinningMeshRenderer: IMeshRenderer
{
};

[uuid("67F42EE0-37DD-4347-9CBF-17EDBC75D2FC")]
interface IGraphicsEngine: IUnknown
{
	HRESULT CreateSwapChain([in] HWND hWnd, [in] UINT width, [in] UINT height);
	HRESULT GetAssetManager([out] IAssetManager** ppAssetManager);
	HRESULT CreateStaticMeshRenderer([out] IMeshRenderer** ppMeshRenderer);
	HRESULT Render();
};
